### PR TITLE
Add MOV_TAG for MOV_OBJECT_JPEG

### PR DESCRIPTION
**Pull request by a-ucontrol**
Hello, please consider this change.
This is needed for [pull](https://github.com/ZLMediaKit/ZLMediaKit/pull/2183)

### CODE REVIEW

**Comment by ireader** [comment]
Tag from ffmepg:

{ AV_CODEC_ID_MJPEG,           MKTAG('m', 'p', '4', 'v') },
{ AV_CODEC_ID_PNG,               MKTAG('m', 'p', '4', 'v') },
{ AV_CODEC_ID_JPEG2000,       MKTAG('m', 'p', '4', 'v') },

**Comment by a-ucontrol** [comment]
I looked [here](https://cconcolato.github.io/mp4ra/codecs.html) 
In my case ffplay works with "jpeg" or "mjpa" tag

**Comment by a-ucontrol** [comment]
I made three files tagged "jpeg", "mp4v" and "mjpa".
ffplay plays "jpeg" and "mjpa" fine, but vlc has audio problems.
I probably need help with this.


https://user-images.githubusercontent.com/55526028/210077650-d1a7d771-5ccd-4795-a274-eab901042cac.mp4

https://user-images.githubusercontent.com/55526028/210077675-864a77f5-64e3-4e8e-a6f0-ec2515411bc5.mp4

https://user-images.githubusercontent.com/55526028/210077696-c5371e39-9514-4534-8196-0831163a142c.mp4

**Comment by ireader** [comment]
OK, I'will check it tomorrow.

**Comment by ireader** [comment]
Please update the lastest code, and try again?

**Comment by a-ucontrol** [comment]
Now it works

https://user-images.githubusercontent.com/55526028/210130061-b81e06f7-1821-4590-a6cb-a3ed462846f9.mp4

For successful compilation I added:
```
#include <errno.h>
```
to libflv/source/vvc-annexbtomp4.c

Thanks and Happy New Year

**Comment by a-ucontrol** [comment]
Can I close this?

**Comment by ireader** [comment]
OK

**Pull request closed without merging**
